apiVersion: v1
kind: Service
metadata:
  name: {{APP_NAME}}
  namespace: {{NAMESPACE}}
spec:
  type: ClusterIP
  selector:
    app: {{APP_NAME}}
  ports:
    - name: http
      port: 80
      targetPort: {{CONTAINER_PORT}}

