apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{FETCHER_APP_NAME}}
  namespace: {{NAMESPACE}}
spec:
  replicas: {{FETCHER_REPLICAS}}
  selector:
    matchLabels:
      app: {{FETCHER_APP_NAME}}
  template:
    metadata:
      labels:
        app: {{FETCHER_APP_NAME}}
    spec:
      imagePullSecrets:
        - name: regcred

      volumes:
        - name: dotenv
          emptyDir: {}

      initContainers:
        - name: write-dotenv
          image: busybox:1.36
          env:
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-auth
                  key: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
          command: ["/bin/sh","-c"]
          args:
            - |
              cat > /work/.env <<EOT
              INFLUXDB_URL=${INFLUXDB_URL}
              INFLUXDB_ORG=${INFLUXDB_ORG}
              INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
              INFLUXDB_TOKEN=$INFLUXDB_TOKEN
              TICKERS=${TICKERS}
              # lowercase keys (fallbacks some builds read)
              org=${INFLUXDB_ORG}
              bucket=${INFLUXDB_BUCKET}
              token=$INFLUXDB_TOKEN
              tickers=${TICKERS}
              EOT
          volumeMounts:
            - name: dotenv
              mountPath: /work

      containers:
        - name: {{FETCHER_APP_NAME}}
          image: {{FETCHER_IMAGE}}:{{FETCHER_TAG}}
          imagePullPolicy: Always
          ports:
            - containerPort: {{FETCHER_CONTAINER_PORT}}
          volumeMounts:
            - name: dotenv
              mountPath: /app/.env
              subPath: .env
          env:
            # canonical
            - name: INFLUXDB_URL
              value: "${INFLUXDB_URL}"
            - name: INFLUXDB_ORG
              value: "${INFLUXDB_ORG}"
            - name: INFLUXDB_BUCKET
              value: "${INFLUXDB_BUCKET}"
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-auth
                  key: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
            - name: TICKERS
              value: "${TICKERS}"
            # lowercase (alternate code paths)
            - name: org
              value: "${INFLUXDB_ORG}"
            - name: bucket
              value: "${INFLUXDB_BUCKET}"
            - name: token
              valueFrom:
                secretKeyRef:
                  name: influxdb-auth
                  key: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
            - name: tickers
              value: "${TICKERS}"

