apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{FETCHER_APP_NAME}}
  namespace: {{NAMESPACE}}
spec:
  replicas: {{FETCHER_REPLICAS}}
  selector:
    matchLabels:
      app: {{FETCHER_APP_NAME}}
  template:
    metadata:
      labels:
        app: {{FETCHER_APP_NAME}}
    spec:
      imagePullSecrets:
        - name: regcred

      # Runtime .env so the app’s hot-reload picks it up
      volumes:
        - name: dotenv
          emptyDir: {}

      initContainers:
        - name: write-dotenv
          image: busybox:1.36
          command: ["/bin/sh","-c"]
          args:
            - |
              cat > /work/.env <<EOT
              # canonical keys
              INFLUXDB_URL=${INFLUXDB_URL}
              INFLUXDB_ORG=${INFLUXDB_ORG}
              INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
              INFLUXDB_TOKEN=${INFLUXDB_ADMIN_TOKEN}
              TICKERS=${TICKERS}
              # aliases some app builds expect
              ORG=${INFLUXDB_ORG}
              BUCKET=${INFLUXDB_BUCKET}
              TOKEN=${INFLUXDB_ADMIN_TOKEN}
              EOT
          volumeMounts:
            - name: dotenv
              mountPath: /work

      containers:
        - name: {{FETCHER_APP_NAME}}
          image: {{FETCHER_IMAGE}}:{{FETCHER_TAG}}
          imagePullPolicy: Always
          ports:
            - containerPort: {{FETCHER_CONTAINER_PORT}}
          volumeMounts:
            - name: dotenv
              mountPath: /app/.env
              subPath: .env

          # (Optional) also expose via env vars; harmless if app prefers /app/.env
          env:
            - name: ORG
              value: "${INFLUXDB_ORG}"
            - name: BUCKET
              value: "${INFLUXDB_BUCKET}"
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-auth
                  key: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
            - name: INFLUXDB_URL
              value: "${INFLUXDB_URL}"
            - name: INFLUXDB_ORG
              value: "${INFLUXDB_ORG}"
            - name: INFLUXDB_BUCKET
              value: "${INFLUXDB_BUCKET}"
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-auth
                  key: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
            - name: TICKERS
              value: "${TICKERS}"

