apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      # Init container adjusts ownership of the data dir to the UID/GID used by the image
      initContainers:
        - name: fix-perms
          image: {{GRAFANA_IMAGE}}
          command: ["/bin/sh","-lc"]
          args:
            - >
              uid=$(stat -c "%u" /usr/share/grafana 2>/dev/null || echo 0);
              gid=$(stat -c "%g" /usr/share/grafana 2>/dev/null || echo 0);
              echo "Adjusting ownership of /var/lib/grafana to ${uid}:${gid}";
              chown -R "${uid}:${gid}" /var/lib/grafana || true;
              chmod -R g+rwX /var/lib/grafana || true
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana

      containers:
        - name: grafana
          image: {{GRAFANA_IMAGE}}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: grafana-admin
          env:
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-auth
                  key: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-provisioning-dashboards
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboards
              mountPath: /var/lib/grafana/dashboards

      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-data
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-provisioning-dashboards
          configMap:
            name: grafana-provisioning-dashboards
        - name: grafana-dashboards
          configMap:
            name: grafana-dashboards

