apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: ${NAMESPACE}
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: ${GRAFANA_NODEPORT}
  externalIPs:
    - ${EXTERNAL_NODE_IP}
