apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: {{NAMESPACE}}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{GRAFANA_STORAGE_SIZE}}

