apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data
  namespace: {{NAMESPACE}}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{INFLUXDB_STORAGE_SIZE}}

