apiVersion: v1
kind: Service
metadata:
  name: {{FETCHER_APP_NAME}}
  namespace: {{NAMESPACE}}
spec:
  type: ClusterIP
  selector:
    app: {{FETCHER_APP_NAME}}
  ports:
    - name: http
      port: 80
      targetPort: {{FETCHER_CONTAINER_PORT}}

